[VIRTS-3453] Single instance of Chrome
mitre/human pull request #18
Opened 2022-01-07 20:00 UTC by djlawren

## Description

These changes refactor the web driver related code to keep only one instance of Chrome open. This is done by changing the `WebDriverHelper` class to a Singleton that opens Chrome in its constructor. The same instance is then used by all web related workflows. They also make it so that only web related workflows need to contain a `WebDriverHelper`. Finally, signal handling was added to the main script to close Chrome when a kill signal is sent to the human since closing is not longer handled by a context manager.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I ran pyhuman will all existing workflows on both a a Windows machine with Chrome installed and a Linux machine without Chrome installed. The Windows machine made use of all four workflows successfully, while the Linux machine only made use of the two workflows that do not require Chrome.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-01-11 02:57 UTC, elegantmoose requested changes

2022-01-11 02:57 UTC, elegantmoose commented on pyhuman/app/workflows/browse_web.py
> +            sleep(2)
Would it be beneficial to have the sleep timer a configurable parameter?

(if not, define the static value in a global at the top of module)

2022-01-11 02:57 UTC, elegantmoose commented on pyhuman/app/workflows/search_web.py
>  from time import sleep
Should we call this workflow 'google_search' or something different.?

I infer the same functionality from the workflows "search_web.py" and "browse_web.py"

2022-01-11 02:57 UTC, elegantmoose commented on pyhuman/app/workflows/search_web.py
> +        sleep(2)
Same comment here about the sleep variable.

2022-01-11 02:57 UTC, elegantmoose commented on pyhuman/app/utility/base_driver.py
> +class Singleton(type):
Like this.

2022-01-11 20:33 UTC, mkultraWasHere approved these changes

2022-01-11 21:10 UTC, elegantmoose requested changes
@djlawren - Woops, jumped the gun. Just noticed a loading issue on local testing. Should line 47 of `/app/human_svc.py` be updated as looks like every workflow `load` function call is getting "driver" parameter when not needed anymore?

2022-01-11 22:45 UTC, elegantmoose approved these changes, later dismissed

2022-01-12 14:04 UTC, mchan143 commented on app/human_svc.py
> +            self.log.error('Error loading extension=%s, %s' % (module_path, e))
Tested this in my Ubuntu VM this morning and got the errors below when standing up the CALDERA server. Adding `webdriver_manager` to the requirements.txt should resolve, but did this come up for anyone else? 

```
2022-01-12 08:52:33 - ERROR (human_svc.py:52 _load_workflow_module) Error loading extension=plugins.human.pyhuman.app.workflows.browse_web, No module named 'webdriver_manager'
2022-01-12 08:52:33 - ERROR (human_svc.py:52 _load_workflow_module) Error loading extension=plugins.human.pyhuman.app.workflows.google_search, No module named 'webdriver_manager'
```

2022-01-12 14:08 UTC, mchan143 commented
After pip installing `webdriver-manager` to resolve the issue I mentioned above, everything else looked great! It should probably be added with a version to human's requirements.txt to get around the plugin load errors. Good work here.

2022-01-12 16:58 UTC, elegantmoose approved these changes

2022-01-12 17:32 UTC, merged